### ISSUE TITLE
add homebrew recipe

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyPlutoSDR#1]
Good reference https://github.com/eblot/homebrew-sdr

**Comment by guruofquality** [comment]
I'm trying to maintain plutosdr here now (pothosware with the other repos) with fixes and tags, etc. @eblot Do you mind me merging/copying your brew recipes for pluto and adi libs into https://github.com/pothosware/homebrew-pothos/wiki So its all in one place? Or do you want to make the commit and or pull request?

**Comment by eblot** [comment]
Sure not. Go ahead and let me know when it's done so I can remove them from my repo.
Thanks.

**Comment by guruofquality** [comment]
@eblot I merged your brew repo into mine. Let me know if you have any issues, and you should have write access as well FYI Thanks! -josh
