### ISSUE TITLE
Ubuntu 18.04 plutosdr build from source error

### ISSUE THREAD

**Issue by wentzlik** [pothosware/SoapyPlutoSDR#12]
is there something missing on my side?
I try to build the soapysdr for Plutosdr on Ubnutu18.04 and after "make" I see it is 100% but the following error message came up and makefile failed.? 

[100%] Linking CXX shared module libPlutoSDRSupport.so
CMakeFiles/PlutoSDRSupport.dir/PlutoSDR_Streaming.cpp.o: In function `rx_streamer::start(int, long long, unsigned long)':
PlutoSDR_Streaming.cpp:(.text+0x14fa): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/PlutoSDRSupport.dir/build.make:175: recipe for target 'libPlutoSDRSupport.so' failed
make[2]: *** [libPlutoSDRSupport.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/PlutoSDRSupport.dir/all' failed
make[1]: *** [CMakeFiles/PlutoSDRSupport.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by guruofquality** [comment]
The build probably needs -lpthread, I think its a build issue that varies from system to system. Can you pull master and try again?

**Comment by wentzlik** [comment]
thanks but how can I pull the master?

**Comment by wentzlik** [comment]
ok I did a pull again and it works Thank you very much...
