### ISSUE TITLE
Doesn't work for me at all

### ISSUE THREAD

**Issue by 0293772929367289** [pothosware/SoapyPlutoSDR#25]
When using "SoapySDRUtil --probe" I get a "segmentation fault". I used different setups. Debian, Kali, Ubuntu. Tried to install from repos if possible, tried to install only from source. Tried the newest firmware 0.30, also the previous 0.29 version. Tried different versions of SoapySDR. And so on. It always comes down to SoapyPlutoSDR not working. 
When I use the command "make" I also get a compilation waring. It is still able to build. I don't have the text anymore since I deleted everything again, but the problem had something to do with  "iio_buffer *buf;" in line 51 and "size_t mtu_size;" in line 54 of the file SoapyPlutoSDR.hpp. I also tried an older version of SoapyPlutoSDR which is still on github. It had no compilation warning, but same "segmentation fault" error.

**Comment by zuckschwerdt** [comment]
Thanks for the report, we need more info to replicate this problem. `mtu_size` is used in very few places and really just a simple value that is passed through.
