### ISSUE TITLE
What is timeoutUS

### ISSUE THREAD

**Issue by samiemostafavi** [pothosware/SoapyPlutoSDR#28]
Hi,

I am working on a SDR board that has a AD9361 like plutoSDR and uses iio drivers. So I am modifying this soapypluto to connect my SDR to other softwares like SRS Lte and etc. 

My problem is that soapypluto doesn't support timestamps and leaves them unused in receive and transmit functions probably because plutoSDR does not have timing support. So I implemented timing functions on my SDR and I modified iio drivers to provide timing functions both on rx and tx.

I tried to figure out what the purpose of timeoutUS parameter is. But I couldnt find anything.
Could you explain what the functionality of timeoutUS is? Because it is both in TX and RX functions.

**Comment by zuckschwerdt** [comment]
See e.g. the [SoapySDRDevice_readStream()](https://pothosware.github.io/SoapySDR/doxygen/latest/Device_8h.html#acd8406fff628dafa224dc5943281e52a) API for a description. We currently don't support a timeout.
