### ISSUE TITLE
Frequency correction API

### ISSUE THREAD

**Issue by kantooon** [pothosware/SoapyPlutoSDR#29]
I've been trying to find out why gr-osmosdr wrapping SoapyPlutoSDR doesn't support setting frequency correction. From a cursory reading of the plutosdr settings it doesn't seem to be implemented at all. Is this right?
Ref. https://github.com/qradiolink/qradiolink/issues/53

**Comment by zuckschwerdt** [comment]
It's not implemented and I don't think the hardware supports this?

**Comment by kantooon** [comment]
Ok, thanks. I think the correction is done in software, not in hardware for most devices, like UHD for example.
