### ISSUE TITLE
Receiving from radio while in IDLE_RX

### ISSUE THREAD

**Issue by samiemostafavi** [pothosware/SoapyPlutoSDR#30]
Hi,

I am using srsLTE on the UE side and I use this driver and ADRV9361 board for that. In the early stages of the connection, after MIB decode, before finding the PLMN, I see these lines from srsLTE ue:
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
SYNC:  Receiving from radio while in IDLE_RX
I could realize that when the UE is in the IDLE state, for some reason the recv function in the driver gets called while the buf is NULL pointer.
Is this a problem which can affect the rest of the connection process? or I can ignore it do you think?

Thanks for your help in advance,
Samie

**Comment by zuckschwerdt** [comment]
I'm not sure about the specifics in this application. In general it's ok to `readStream()` at any time between `setupStream()` and `closeStream()`. If the stream is not active you'll get `0` bytes.
It's important that the `buffs` given are not `NULL` though -- but you'll see an instant crash if they are ;)
