### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by Jeija** [pothosware/SoapyPlutoSDR#38]
It has been quite some time since the last release of SoapyPlutoSDR, version 0.2.0 on June 22nd 2019.
Since then, there have been some small, but pretty important changes. For instance, a project of mine that uses SoapyPlutoSDR needs [this](https://github.com/pothosware/SoapyPlutoSDR/commit/bbd16b0b17ce16fc2d0553914b763818f25dfc03) fix from March 3rd 2020 to function properly, but my distribution ships the release version from 2019.

Is there any reason not to tag a release to get the bugfixes and improvements since then out there?

**Comment by guruofquality** [comment]
done https://github.com/pothosware/SoapyPlutoSDR/releases/tag/soapy-plutosdr-0.2.1

thanks!
