### ISSUE TITLE
SoapyPlutoSDR included in Pothos?

### ISSUE THREAD

**Issue by androbi-com** [pothosware/SoapyPlutoSDR#40]
Please forgive me if this is a stupid question, but should SoapyPlutoSDR be included with the Pothos distribution? This [page](https://github.com/pothosware/SoapyPlutoSDR/wiki) made me think so, but my device is not detected. And, no "pluto" related file in lib/SoapySDR/modules0.8. I installed the latest release PothosSDR-2021.02.28-vc16-x64. SDR Console works on the same machine. Any hints for getting this to work?

**Comment by zuckschwerdt** [comment]
It's there but as component: https://github.com/pothosware/PothosSDR/blob/master/SetupNSIS.cmake#L153
You need to enable "PlutoSDR SoapySDR binding (experimental)" (in the "experimental" group) while installing.

**Comment by androbi-com** [comment]
Thanx a lot! Maybe a short note about the experimental status could be added to (https://github.com/pothosware/SoapyPlutoSDR/wiki)?

**Comment by guruofquality** [comment]
Just for reference this is the reason:

* https://github.com/pothosware/SoapyPlutoSDR/issues/24
* https://github.com/analogdevicesinc/libiio/issues/586

I had to make it optional because it can mess with other libusb devices, and it was an ongoing support issue that kept coming up.
