### ISSUE TITLE
ERROR: Unable to claim interface : Device or resource busy

### ISSUE THREAD

**Issue by eljuligallego** [pothosware/SoapyPlutoSDR#41]
Hi,
I'm new to pothosflow, have more experience with gnuradio.

Just installed in ubuntu 18.04 this driver for running some examples in Pothosflow with the adalm pluto but when load the topology with the plutosdr driver the message window give this error and no data is get to the flow diagram.

All the installation process seems ok and the SoapySDRUtil --probe="driver=plutosdr,hostname=192.168.2.1" command works correctly.

any ideas?.

**Comment by zuckschwerdt** [comment]
This was likely fixed now with #50.
