### ISSUE TITLE
PlutoSDR only works for a short time (readStream timeout!)

### ISSUE THREAD

**Issue by Hiermur** [pothosware/SoapyPlutoSDR#55]
Hello,

I'm trying to get a Pluto running locally attached to a Debian PC with OpenWebRX. It also works, but after a short while it kicks out, the system load ramps up to the max and the log says:

WARNING: SoapySDR::Device::readStream timeout!

And the log is flooded.

SoapySDRUtil --probe=driver=plutosdr
######################################################
######################################################

Probe device driver=plutosdr
ERROR: Unable to create Avahi DNS-SD client :Daemon not running
[WARNING] Unable to scan ip: -26

[INFO] Opening PlutoSDR #0 usb:2.9.5...

----------------------------------------------------
-- Device identification
----------------------------------------------------
  driver=PlutoSDR
  hardware=ADALM-PLUTO
  ad9361-phy,model=ad9364
  ad9361-phy,xo_correction=39999947
  backend_version=0.24 (git tag: v0.24)
  fw_version=v0.35
  hw_model=Analog Devices PlutoSDR Rev.B (Z7010-AD9364)
  hw_model_variant=1
  hw_serial=104473dc5993001711003300d1172a962c
  library_version=0.24 (git tag: e598e4b)
  local,kernel=5.10.0-98231-g9dfba10b795d
  uri=usb:2.9.5
  usb,idProduct=b673
  usb,idVendor=0456
  usb,libusb=1.0.24.11584
  usb,product=PlutoSDR (ADALM-PLUTO)
  usb,release=2.0
  usb,serial=104473dc5993001711003300d1172a962c
  usb,vendor=Analog Devices Inc.

----------------------------------------------------
-- Peripheral summary
----------------------------------------------------
  Channels: 1 Rx, 1 Tx
  Timestamps: NO
  Sensors: xadc_temp0, xadc_voltage0, xadc_voltage1, xadc_voltage2, xadc_voltage3, xadc_voltage4, xadc_voltage5, xadc_voltage6, xadc_voltage7, xadc_voltage8, adm1177_current0, adm1177_voltage0, ad9361-phy_temp0, ad9361-phy_voltage2

----------------------------------------------------
-- RX Channel 0
----------------------------------------------------
  Full-duplex: YES
  Supports AGC: YES
  Stream formats: CS8, CS12, CS16, CF32
  Native format: CS16 [full-scale=2048]
  Antennas: A_BALANCED
  Full gain range: [0, 73] dB
    PGA gain range: [0, 73] dB
  Full freq range: [70, 6000] MHz
    RF freq range: [70, 6000] MHz
  Sample rates: [0.260417, 61.44] MSps
  Filter bandwidths: 0.2, 1, 2, 3, 4, 6, 7, 8, 9, 10 MHz

----------------------------------------------------
-- TX Channel 0
----------------------------------------------------
  Full-duplex: YES
  Supports AGC: NO
  Stream formats: CS8, CS12, CS16, CF32
  Native format: CS16 [full-scale=32768]
  Antennas: A
  Full gain range: [0, 89] dB
    PGA gain range: [0, 89] dB
  Full freq range: [70, 6000] MHz
    RF freq range: [70, 6000] MHz
  Sample rates: [0.260417, 61.44] MSps
  Filter bandwidths: 0.2, 1, 2, 3, 4, 6, 7, 8, 9, 10 MHz

Does one of you have an idea?

**Comment by zuckschwerdt** [comment]
This might have been fixed by #57.
