### ISSUE TITLE
Make a new 0.2.2 release

### ISSUE THREAD

**Issue by dl1jbe** [pothosware/SoapyPlutoSDR#59]
As there are quite some corrections and fixes since 0.2.1 it would be nice to have an actual release (or at least a tag).

**Comment by guruofquality** [comment]
agreed, any comments on the updated changelog notes? https://github.com/pothosware/SoapyPlutoSDR/pull/61

**Comment by guruofquality** [comment]
https://github.com/pothosware/SoapyPlutoSDR/releases/tag/soapy-plutosdr-0.2.2

:-)

**Comment by dl1jbe** [comment]
Looks good. Thanks.
